# Name of the action
name: API Validator

# description of the action
description: Validates that API responses match what is documented in OpenAPI specifications.

# input parameters to the action
inputs:
  spec_file:
    required: true
    description: Path to the OpenAPI specficaion file in your repo you wish to validate
  step_file:
    required: true
    description: Path to the corresponding step file in your repo you wish to validate
  fail_fast:
    required: false
    description: Flag indicating whether the action should report test failures and terminate immediately
  verbose:
    required: false
    description: Flag indicating whether the action should output detailed stacktrace

# describes how our action is run
runs:
  using: docker
  image: "Dockerfile"

# For publishing purposes
branding:
  icon: "https://brand.bandwidth.com/wp-content/uploads/Bandwidth-Icon-1.png"
  color: "#079CEE" # white background on logo
