# action.yml
name: 'Deploy'
description: 'Deploys the python sdk to PYPI'
runs:
  using: 'composite'
  steps:
    - run: |
        pip install twine
        pip install wheel
        python setup.py sdist bdist_wheel
        twine upload dist/* -u __token__ -p $PYPI_API_KEY
      shell: bash
