name: Unit Tests
on:
  pull_request:
  workflow_dispatch:

env:
  PYPONY_RELEASE_VERSION: 0.0.0

concurrency:
  group: pypony-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          make install-dependencies

      - name: Test
        run: make test

      - name: Install CLI
        run: make install-cli
